# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170705_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='image/%Y/%m', verbose_name='封面图'),
        ),
    ]
